In [7]:
from src.cfbd_client import get_games_by_year
import pandas as pd

df_2025 = get_games_by_year(2025)

print(df_2025.shape)
df_2025.info()
df_2025.head()

(3651, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3651 entries, 0 to 3650
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          3651 non-null   int64
 1   season                      3651 non-null   int64
 2   week                        3651 non-null   int64
 3   seasonType                  3651 non-null   object
 4   startDate                   3651 non-null   datetime64[ns, UTC]
 5   startTimeTBD                3651 non-null   bool
 6   completed                   3651 non-null   bool
 7   neutralSite                 3651 non-null   bool
 8   conferenceGame              3651 non-null   bool
 9   venueId                     3643 non-null   float64
 10  venue                       3643 non-null   object
 11  homeId                      3651 non-null   int64
 12  homeTeam                    3651 non-null   object
 13  homeConference              3635 non-null   object
 14  homeClassification          3635 non-null   object
 15  homePoints                  1950 non-null   float64
 16  homeLineScores              1948 non-null   object
 17  homePostgameWinProbability  819 non-null    float64
 18  homePregameElo              878 non-null    float64
 19  homePostgameElo             477 non-null    float64
 20  awayId                      3651 non-null   int64
 21  awayTeam                    3651 non-null   object
 22  awayConference              3605 non-null   object
 23  awayClassification          3605 non-null   object
 24  awayPoints                  1950 non-null   float64
 25  awayLineScores              1948 non-null   object
 26  awayPostgameWinProbability  819 non-null    float64
 27  awayPregameElo              753 non-null    float64
 28  awayPostgameElo             352 non-null    float64
 29  excitementIndex             780 non-null    float64
 30  highlights                  3651 non-null   object
 31  notes                       44 non-null     object
 32  attendance                  0 non-null      object
dtypes: bool(4), datetime64[ns, UTC](1), float64(10), int64(5), object(13)
memory usage: 841.6+ KB

,id,season,week,seasonType,startDate,startTimeTBD,completed,neutralSite,conferenceGame,venueId,...,awayClassification,awayPoints,awayLineScores,awayPostgameWinProbability,awayPregameElo,awayPostgameElo,excitementIndex,highlights,notes,attendance
0,401756846,2025,1,SeasonType.REGULAR,2025-08-23 16:00:00+00:00,False,True,True,True,3504.0,...,DivisionClassification.FBS,24.0,"[7, 0, 7, 10]",0.798456,1616.0,1619.0,6.029094,,Aer Lingus College Football Classic,None
1,401767476,2025,1,SeasonType.REGULAR,2025-08-23 17:00:00+00:00,False,True,False,True,3779.0,...,DivisionClassification.FCS,6.0,"[3, 0, 3, 0]",0.290214,NaN,NaN,5.126499,,None,None
2,401760371,2025,1,SeasonType.REGULAR,2025-08-23 20:00:00+00:00,False,True,False,False,6501.0,...,DivisionClassification.FCS,31.0,"[10, 7, 7, 7]",0.021213,NaN,NaN,9.598562,,None,None
3,401767126,2025,1,SeasonType.REGULAR,2025-08-23 20:30:00+00:00,False,True,False,False,4765.0,...,DivisionClassification.FCS,42.0,"[7, 7, 14, 14]",0.971885,NaN,NaN,4.943514,,None,None
4,401756847,2025,1,SeasonType.REGULAR,2025-08-23 22:30:00+00:00,False,True,False,False,3833.0,...,DivisionClassification.FBS,7.0,"[7, 0, 0, 0]",0.000000,1490.0,1441.0,3.783041,,None,None

In [8]:
import os
os.makedirs("../Data/Raw", exist_ok=True)
df_2025.to_csv("../Data/Raw/games_2025.csv", index=False)

In [9]:
from src.data_cleaning import clean_games

df_2025_clean = clean_games(df_2025)
df_2025_clean.head()

,id,season,week,seasonType,startDate,startTimeTBD,completed,neutralSite,conferenceGame,venueId,...,awayClassification,awayPoints,awayLineScores,awayPostgameWinProbability,awayPregameElo,awayPostgameElo,excitementIndex,highlights,notes,attendance
0,401756846,2025,1,SeasonType.REGULAR,2025-08-23 16:00:00+00:00,False,True,True,True,3504.0,...,DivisionClassification.FBS,24.0,"[7, 0, 7, 10]",0.798456,1616.0,1619.0,6.029094,,Aer Lingus College Football Classic,None
1,401767476,2025,1,SeasonType.REGULAR,2025-08-23 17:00:00+00:00,False,True,False,True,3779.0,...,DivisionClassification.FCS,6.0,"[3, 0, 3, 0]",0.290214,NaN,NaN,5.126499,,None,None
2,401760371,2025,1,SeasonType.REGULAR,2025-08-23 20:00:00+00:00,False,True,False,False,6501.0,...,DivisionClassification.FCS,31.0,"[10, 7, 7, 7]",0.021213,NaN,NaN,9.598562,,None,None
3,401767126,2025,1,SeasonType.REGULAR,2025-08-23 20:30:00+00:00,False,True,False,False,4765.0,...,DivisionClassification.FCS,42.0,"[7, 7, 14, 14]",0.971885,NaN,NaN,4.943514,,None,None
4,401756847,2025,1,SeasonType.REGULAR,2025-08-23 22:30:00+00:00,False,True,False,False,3833.0,...,DivisionClassification.FBS,7.0,"[7, 0, 0, 0]",0.000000,1490.0,1441.0,3.783041,,None,None

## Multi-Year Data Pull

In [10]:
from src.cfbd_client import get_games_by_year
from src.data_cleaning import clean_games
import pandas as pd
import os
from time import sleep

raw_path = "../Data/Raw"
os.makedirs(raw_path, exist_ok=True)

START_YEAR = 2000
END_YEAR = 2025

all_years = []

for year in range(START_YEAR, END_YEAR + 1):
    print(f"Fetching {year} season...")

    try:
        df = get_games_by_year(year)
        df = clean_games(df)
        df["season"] = year

        output_path = os.path.join(raw_path, f"games_{year}.csv")
        df.to_csv(output_path, index=False)

        all_years.append(df)

        sleep(0.5)

    except Exception as e:
        print(f"⚠️ Failed for {year}: {e}")

df_all = pd.concat(all_years, ignore_index=True)
print(f"\nCombined dataset shape: {df_all.shape}")

df_all.to_csv(os.path.join(raw_path, "games_all_2000_2025.csv"), index=False)

df_all.head()

Fetching 2000 season...
Fetching 2001 season...
Fetching 2002 season...
Fetching 2003 season...
Fetching 2004 season...
Fetching 2005 season...
Fetching 2006 season...
Fetching 2007 season...
Fetching 2008 season...
Fetching 2009 season...
Fetching 2010 season...
Fetching 2011 season...
Fetching 2012 season...
Fetching 2013 season...
Fetching 2014 season...
Fetching 2015 season...
Fetching 2016 season...
Fetching 2017 season...
Fetching 2018 season...
Fetching 2019 season...
Fetching 2020 season...
Fetching 2021 season...
Fetching 2022 season...
Fetching 2023 season...
Fetching 2024 season...
Fetching 2025 season...

/var/folders/85/gv9dnstn1tn96gql2f7mj15h0000gn/T/ipykernel_34740/4109795953.py:33: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat(all_years, ignore_index=True)

Combined dataset shape: (44004, 33)

,id,season,week,seasonType,startDate,startTimeTBD,completed,neutralSite,conferenceGame,homeId,...,awayPregameElo,awayPostgameElo,highlights,attendance,venueId,venue,homePostgameWinProbability,awayPostgameWinProbability,excitementIndex,notes
0,63071,2000,1,SeasonType.REGULAR,2000-08-26 00:00:00+00:00,False,True,False,False,2641,...,1324.0,1289.0,,NaN,NaN,None,NaN,NaN,NaN,None
1,63068,2000,1,SeasonType.REGULAR,2000-08-26 00:00:00+00:00,False,True,False,False,52,...,1603.0,1572.0,,NaN,NaN,None,NaN,NaN,NaN,None
2,63069,2000,1,SeasonType.REGULAR,2000-08-26 00:00:00+00:00,False,True,False,False,2306,...,1344.0,1349.0,,NaN,NaN,None,NaN,NaN,NaN,None
3,63070,2000,1,SeasonType.REGULAR,2000-08-26 00:00:00+00:00,False,True,False,False,2348,...,NaN,NaN,,NaN,NaN,None,NaN,NaN,NaN,None
4,63072,2000,1,SeasonType.REGULAR,2000-08-27 00:00:00+00:00,False,True,False,False,30,...,1789.0,1712.0,,NaN,NaN,None,NaN,NaN,NaN,None